# render.yaml – deploys LibreChat + free Postgres on Render
services:
  - type: web
    name: librechat
    env: docker            # Render will use the Dockerfile already in the repo
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT          # Render sets PORT for you at runtime, but we keep a default
        value: 8080
      # --------- required by LibreChat itself ----------
      - key: DOMAIN_CLIENT
        value: https://$(RENDER_EXTERNAL_HOSTNAME)
      - key: NEXTAUTH_URL
        value: https://$(RENDER_EXTERNAL_HOSTNAME)
      - key: SESSION_SECRET          # make one with `openssl rand -hex 32`
        generateValue: true
      # -------------------------------------------------
